### ISSUE TITLE
Make clearing the screen faster

### ISSUE THREAD

**Issue by jelly** [jelly/e-ink-status-display#2]
Currently it takes 26 seconds including init to clear the display that's too slow.

* A lot of CPU usage ~ 100%
* spidev/numpy usage might be more optional

**Comment by jelly** [comment]
Using a newer (damn you Debian) spidev with writebytes2() and sending all data at once is 16 seconds faster.

```
time PYTHONPATH=/home/pi/py-spidev/build/lib.linux-armv6l-3.5/ python3 test.py
Clear...

real    0m10.281s
user    0m3.394s
sys     0m0.168s
```

**Comment by jelly** [comment]
Setting the SPI max speed to 8 MHz makes it 1 second faster and 5 seconds is spend in wait_on_idle waiting on the pin to become low.

**Comment by jelly** [comment]
Or try a reset and then a refresh without data.

**Comment by sebastius** [comment]
you're sending twice the amount of data required. Change the for loop to 

for _ in range (0, self.width // 2 * self.height):
    epdconfig.SPI.writebytes(data)

and you are done.

**Comment by jelly** [comment]
10 seconds now, good enough!
